// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, username, password, role) VALUES (
  gen_random_uuid(),
  $1,
  $2,
  $3
) RETURNING id, username, password, avatar_id, role
`

type CreateUserParams struct {
	Username string
	Password string
	Role     UserRole
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.AvatarID,
		&i.Role,
	)
	return i, err
}
